### ISSUE TITLE
Data coercion 

### ISSUE THREAD

**Issue by vincentjames501** [michaelklishin/validateur#39]
I chose to use Validateur over another tool like Schema due to the fact that the error messages are easily human readable. While I realize this isn't what Validateur is all about, it would be nice to add a new namespace that can do data coercion for you.  I'm thinking of something like the following use case:

Consider a JSON POST body of:

```json
{"subscriptionSize": 250}
```

Versus a form encoded POST of:

```
?subscriptionSize=250
```

In the case of JSON (using ring and popular middleware), the type of subscriptionSize is a number and in the case of the form encoded params the type is a String.

This causes a validation such as below to be inconsistent where it would validate correctly for the JSON request but not the form encoded request:

```clojure
(def ^:private my-validateur
  (validation-set
    (presence-of #{:other-param :subscription-size} :any true)
    (numericality-of :subscription-size :only-integer false :gte 0 :allow-nil true)))
```

It would be nice if Validator could create a new namespace that can coerce your data depending on your validation specified. Something like the following:

```clojure
(defn handle-request 
  [request]
  (let [coerced-params (validateur.coercer/coerce my-validateur (:params request))
         errors (my-validateur coerced-params)]
    (if (empty? errors)
      (do-stuff coerced-params)
      (reject-stuff errors))))
```

This is just intended to spark a conversation. Thoughts?

**Comment by michaelklishin** [comment]
How would `v.coercer/coerce` work in the provided example? And for what data types?

**Comment by vincentjames501** [comment]
In the example, it would coerce the string value of "250" to a number with value 250.

i.e. the following tests would pass

```clojure
(assert (= {:subscription-size 250} (validateur.coercer/coerce my-validateur {:subscription-size "250"})))
(assert (= {:subscription-size 250} (validateur.coercer/coerce my-validateur {:subscription-size 250})))
(assert (= {:subscription-size nil} (validateur.coercer/coerce my-validateur {:subscription-size nil})))
(assert (= {} (validateur.coercer/coerce my-validateur {})))
```

Again, this is meant to start a conversation. I love how Schema does this as it makes sure your business logic doesn't have to worry about the types of your data and that the data is validated by the time it arrives. It would just be awesome if we could somehow take our validation structure (which we're essentially defining a schema) and coerce the data if possible.

**Comment by michaelklishin** [comment]
This sounds like something a complete separate library can do, nothing specific to Validateur or depending on it. I'm also not sure how much coercion can be done by a single function.
