### ISSUE TITLE
Travis build doesn't seem to run tests?

### ISSUE THREAD

**Issue by michalmarczyk** [michaelklishin/validateur#49]
Here's a build from December 2014 that reports having run "0 tests containing 0 assertions": https://travis-ci.org/michaelklishin/validateur/jobs/43995750 –

> Performing task 'test' with profile(s): 'base,system,user,provided,dev'
> lein test user
> Ran 0 tests containing 0 assertions.
> 0 failures, 0 errors.

And so on for other profiles.

Similarly I just noticed that the Travis builds associated with my recent PRs also seem to claim to have had no tests to run, except those using cljc (the one associated with #47 and those which happened after that merge) appear to be running ClojureScript tests:

> Running ClojureScript test: phantom
> Using ClojureScript version 1.7.228
> Testing validateur.test.validation-test
> Ran 74 tests containing 343 assertions.
> 0 failures, 0 errors.

Running `lein all do clean, test` produces the expected output on my local machine (and has for all my recent PRs).

**Comment by michaelklishin** [comment]
Yeah, I'm not sure what may be going on.

**Comment by michaelklishin** [comment]
Addressed in master, e.g. see https://travis-ci.org/michaelklishin/validateur/builds/323098619.
